[PUB-3200] Implement global appshell
bufferapp/buffer-publish pull request #1657
Opened 2020-12-16 17:48 UTC by anafilipadealmeida

## Description
Implement Global AppShell

## Context & Notes
https://buffer.atlassian.net/browse/PUB-3200

## Screenshots (if appropriate)

## Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have tested different user stories. 
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

#### Staging Deployment

To visit the URL of the staging deployment, please click "Show all checks" at the bottom of this PR and click "details" next to `bufferbotbrains/cicd-buffer-publish-legacy`

2021-02-08 22:36 UTC, hamstu commented on packages/app-pages/components/AppPages/index.jsx
> +  // se nesta altura não houver resposta do pedido de graphql isto lixa-se tudo
🇵🇹 ❤️

2021-02-09 20:46 UTC, anafilipadealmeida commented on packages/app-pages/components/AppPages/index.jsx
> +  // se nesta altura não houver resposta do pedido de graphql isto lixa-se tudo
It was a temporary mental note for myself. The weird thing is that google translate is wrong when translating this to English, gives it the opposite meaning 😂

2021-02-09 20:51 UTC, hamstu commented on packages/app-pages/components/AppPages/index.jsx
> +  // se nesta altura não houver resposta do pedido de graphql isto lixa-se tudo
Haha, I didn't even translate it until just now! So you're saying it's NOT fine?

2021-02-10 15:13 UTC, anafilipadealmeida commented on packages/app-pages/components/AppPages/index.jsx
> +  // se nesta altura não houver resposta do pedido de graphql isto lixa-se tudo
Yes, it means it's not fine! Now with the loading gate this is no longer a problem 😄

2021-03-01 14:11 UTC, anafilipadealmeida commented on packages/app-shell/package.json
> +    "@bufferapp/app-shell": "2.0.1-orgswitcher.7+2393313"
I'd deploy this with our beta branch so we are not blocked and bring the appshell changes to the frontend gathering tomorrow

2021-03-01 17:29 UTC, albennett commented on packages/app-shell/package.json
> +    "@bufferapp/app-shell": "2.0.1-orgswitcher.7+2393313"
Sounds great. I'll follow up with Mike on this [PR](https://github.com/bufferapp/app-shell/pull/11): as I'll need these changes for the no access pages. If he deploys it first, I'll merge main into your app shell branch and publish to beta.

2021-03-01 18:10 UTC, albennett approved these changes
Great perseverance with this, Ana! 🙌 

On a side note, we'll need to run `api-gateway` to get publish to load locally going forward. I wonder if we can get this added to our `./dev up publish` script.  ✨ I can reach out to infra about adding the change.

2021-03-01 21:08 UTC, hamstu requested changes
You deserve a sabbatical after this PR @anafilipadealmeida. 👏🏻 

But seriously — thanks for sticking through this. I hope we can improve things going forward to make this sort of work more streamlined.

Left one small piece of feedback, but otherwise this is great!

I'd love to get this deployed soon, but wanted to ask how you feel about it in terms of testing. Are there any use-cases we haven't tested yet? Perhaps you can run through a few different scenarios / accounts in staging so we can be confident here.

2021-03-01 21:08 UTC, hamstu commented on packages/app-pages/components/AppPages/index.jsx
> +    selectedOrgInAppShell !== orgIdFromRoute && !!orgIdFromRoute;
This line confused me a bit at first. Can we make it more clear?

```suggestion
    (selectedOrgInAppShell !== orgIdFromRoute) && (orgIdFromRoute !== undefined);
```

Adding some parens for clarity, and then I'd prefer a `!== undefined` or `!== null` check at the end (Do you know which it would be?) since the `!!` is handy but not always clear at first glance.

2021-03-02 00:11 UTC, anafilipadealmeida commented on packages/app-pages/components/AppPages/index.jsx
> +    selectedOrgInAppShell !== orgIdFromRoute && !!orgIdFromRoute;
Hey @hamstu, I understand the concern about clear code, but I'm not sure I see a problem with double negation. It's very useful as it considers both `undefined`, `null`, `false` and empty strings, which is a great validation here. Doing a quick search we use the double negation to get a boolean 31 times in our codebase. How would you feel if instead of changing it I added a comment explaining it? As for the parens, our linter/prettier will remove then 😅

2021-03-02 00:13 UTC, hamstu commented on packages/app-pages/components/AppPages/index.jsx
> +    selectedOrgInAppShell !== orgIdFromRoute && !!orgIdFromRoute;
Thanks @anafilipadealmeida! A comment sounds like a great solution here! Maybe it was just my early-morning brain struggling to understand things 🙈

2021-03-02 00:13 UTC, hamstu approved these changes

2021-03-02 13:34 UTC, anafilipadealmeida commented
@hamstu, in terms of testing, I've listed the use cases above and I've gone through each of them. Like the previous org switcher implementation, there's always a chance of a race condition (due to the fact that currently profiles and orgs are separated entities), but I haven't seen it yet, so I'll deploy this 🤞

2021-03-02 13:36 UTC, merged