[PUB-3232] Update the "what would you like to post" CTA (& A/B test)
bufferapp/buffer-publish pull request #1812
Opened 2021-06-23 19:49 UTC by daltino

### Description

Added a new Create Post button which would show close to the Calendar button group in the header in queue view. The “What would you like to share” is gone; replaced by this blue “Create Post” button based on a feature flip, `create_post_button_queue` assigned on an org level.

### Context & Notes

As a Buffer customer, when I’m my queue view it should be really clear and compelling for where to click to create a cross-platform post

https://buffer.atlassian.net/browse/PUB-3232

### Screenshots (if appropriate)
https://share.getcloudapp.com/geugp5j4
https://share.getcloudapp.com/rRujW4yZ

### Best Practices Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-07-05 18:51 UTC, MayaUribe requested changes
Hey @daltino! Thank you for your work!
I left some comments over here! I'll be taking a look at the backend one now :D

2021-07-05 18:51 UTC, MayaUribe commented on packages/server/formatters/entitlements.js
> +  CREATE_POST_BUTTON: 'createPostButton',
Hey, @daltino I don't think this should be an entitlement, this is why:
- Entitlements are "features" an organization is entitled to, these are org level and **depend on the billing plan**, when we use an entitlement, this means it's somehow bound to the plan.
- A feature flip on the other hand is used to roll out a new feature, these are user level, and we use them to experiment or do a roll-out by percentage, and to be able to turn things on and off.

2021-07-05 18:51 UTC, MayaUribe commented on packages/server/parsers/orgParser.js
> +  hasCreatePostButtonFeature: orgData.ownerFeatures.includes(entitlements.CREATE_POST_BUTTON),
@daltino in here you are checking against `orgData.ownerFeatures` which are the featureFlips for the organization owner, and this entitlement in any case would be in the organization level

2021-07-05 18:51 UTC, MayaUribe commented on packages/server/parsers/orgParser.js
> +  hasCreatePostButtonFeature: orgData.ownerFeatures.includes(entitlements.CREATE_POST_BUTTON),
For percentage rollouts (10, 50%, etc) we use the feature flips, the problem is that we do this at the user level, and we are aiming to do this at the organization level, this is something we don't currently have implemented in the backend.

However this should be transparent in the frontend, I'm thinking this should look something like `orgData.features.includes(features.CREATE_POST_BUTTON)`

2021-07-05 19:20 UTC, daltino commented on packages/server/formatters/entitlements.js
> +  CREATE_POST_BUTTON: 'createPostButton',
Yh I thought about this as well, do we have a file where we store feature flips in code? @MayaUribe

2021-07-06 07:13 UTC, MayaUribe commented on packages/server/formatters/entitlements.js
> +  CREATE_POST_BUTTON: 'createPostButton',
@daltino as I mentioned the other day in our chat, you can use the calendar feature as an example, because the features are user-based, you need to look at the `userParser` instead:
https://github.com/bufferapp/buffer-publish/blob/c62eac7d6dda59de71b0becd289cf284614d1e94/packages/server/parsers/userParser.js#L38

2021-07-06 12:33 UTC, daltino commented on packages/server/formatters/entitlements.js
> +  CREATE_POST_BUTTON: 'createPostButton',
Ok so its the `userParser` 😄  thanks for reminding me on this @MayaUribe

2021-07-06 15:55 UTC, daltino commented on packages/server/parsers/orgParser.js
> +  hasCreatePostButtonFeature: orgData.ownerFeatures.includes(entitlements.CREATE_POST_BUTTON),
I agree on this one, when we pair we can discuss in detail @MayaUribe

2021-07-07 12:10 UTC, MayaUribe commented
Hey @daltino this one is 99% there! when you get the tests fixed this one should be ready to go 😊🚀

2021-07-07 13:26 UTC, MayaUribe commented on packages/queue/middleware.js
> +      dispatch(analyticsActions.trackEvent('Composer Opened Via Share Textbox', ctaProperties));
Hey @daltino I think we should confirm here because, on @jwinternheimer's PR, he mentioned: 

> Initially I said that I'd add two separate events to track clicks of each, but I thought that both could be covered with a generic Composer Opened event.

But here you are tracking it as two: `Composer Opened Via Share Textbox` and `Composer Opened Via Create Post Button`, I think the CTA properties look fine, which is what he also mentioned on his PR.

2021-07-07 13:30 UTC, daltino commented on packages/queue/middleware.js
> +      dispatch(analyticsActions.trackEvent('Composer Opened Via Share Textbox', ctaProperties));
Ok so both should have same name `Composer Opened` @MayaUribe

2021-07-07 13:46 UTC, MayaUribe reviewed
I left a couple of comments @daltino and one question for @letsbleachthis 😄

2021-07-07 13:46 UTC, MayaUribe commented on packages/shared-components/QueueItems/Header/index.jsx
> +                type={'primary'}
A very tiny one, but the curly braces aren't necessary for this line:
```suggestion
                type="primary"
```

2021-07-07 13:46 UTC, MayaUribe commented on packages/shared-components/QueueItems/Header/index.jsx
> +                size="small"
A styling detail where we could use @letsbleachthis's help 😊

The size of the button doesn't look like the one on the image in Jira:
<img src="https://user-images.githubusercontent.com/988972/124769177-8b695c80-df39-11eb-8b52-289e86eef402.jpg" width="500px" />

How it is now, it looks smaller:
<img src="https://user-images.githubusercontent.com/988972/124769532-d3887f00-df39-11eb-955d-452eb2e07218.jpg" width="500px" />

And if we use the use the "normal" size, it'd look like this:
<img src="https://user-images.githubusercontent.com/988972/124769736-02065a00-df3a-11eb-83d0-8ccc6060500f.jpg" width="500px" />

I'd say the one that looks slightly bigger would be better?

2021-07-07 15:59 UTC, letsbleachthis commented on packages/shared-components/QueueItems/Header/index.jsx
> +                size="small"
> A styling detail where we could use @letsbleachthis's help 😊
> 
> The size of the button doesn't look like the one on the image in Jira:
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/988972/124769177-8b695c80-df39-11eb-8b52-289e86eef402.jpg">
> 
> How it is now, it looks smaller:
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/988972/124769532-d3887f00-df39-11eb-955d-452eb2e07218.jpg">
> 
> And if we use the use the "normal" size, it'd look like this:
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/988972/124769736-02065a00-df3a-11eb-83d0-8ccc6060500f.jpg">
> 
> I'd say the one that looks slightly bigger would be better?

Ya, I'd agree @MayaUribe! One day, we hopefully will replace the old button group with the [new segmented control](https://www.figma.com/file/e98Oo1Z8lVI74Oks8zqr6f/BDS-Segmented-Control?node-id=1%3A2) component that Mw just built, and then they'll match in size, but for now — let's use the "normal" primary button size that is slightly bigger.

2021-07-07 16:36 UTC, daltino commented on packages/shared-components/QueueItems/Header/index.jsx
> +                size="small"
Ok @MayaUribe  @letsbleachthis I will use the "normal" size

2021-07-07 18:26 UTC, merged