Replace AppShell with Navigator
bufferapp/buffer-publish pull request #1830
Opened 2021-07-14 23:11 UTC by federicoweber

### Description
To replace the former AppShell with the new dynamically served Navigator.

This takes care of the following breaking changes:

import Navigator from a static URL and remove the AppSheel dependency
implement a layout style to properly render the Navigator and the App
decouple the User Context from the AppShell
migrate AppShell modals opening to the new APIs
retrigger accounts-related queries on Organization change.

### Context & Notes
Also see this [doc.](https://paper.dropbox.com/doc/Publishing-appshell-org-switcher--BOBRAnd_9S1YJSSpRE5rPaHyAg-5VPgLr3C6brHMfz54cqJ6) for relevant interactions with the org switcher

### Screenshots (if appropriate)

### Best Practices Checklist

-   [X] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [X] I have tested different user stories.
-   [X] I have identified similar or related features and tested they are still working.
-   [X] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [X] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-07-14 23:11 UTC, federicoweber commented on packages/accountContext/index.js
> +`
I think this is covering all the info we need in Publishing. Let me know if I need to add anything else.

2021-07-14 23:13 UTC, federicoweber commented on packages/accountContext/index.js
> +};
This replace the `useUser` context from the AppShell

2021-07-14 23:16 UTC, federicoweber commented on packages/web/components/LoadingGate/index.jsx
> +
This is used to update Publishing organization if that is changed from the Navigator.

It's working well, but I noticed it's not updating the URL, and the selected profile. Not sure if that's expected or a bug.
![Publish navigator](https://user-images.githubusercontent.com/992920/125704616-b7a9d914-4eee-4492-85dd-358e31948084.gif)

2021-07-14 23:17 UTC, federicoweber commented on packages/web/index.jsx
> +  }, [])
This initializes the `account` context, and re-fetch it on org change

2021-07-14 23:21 UTC, federicoweber commented
I'm having some issues with the staging environment, the `enableApplicationModes` RPC is failing with the following response.
```
{"error":"404 - \"{\\\"error\\\":\\\"Application modes could not be found\\\",\\\"code\\\":1000}\"","code":5000,"stack":false,"handled":false}
```
Any idea what is causing that?

2021-07-15 12:39 UTC, anafilipadealmeida reviewed
I was only able to test the initial loading and to debug the interaction with the store, so I left a comment with what I think is missing there. 
I have a question: how do we now load publish with the navigator? I wanted to quickly check the route change scenarios with the navigator as well!
<img width="1673" alt="Screenshot 2021-07-15 at 13 34 32" src="https://user-images.githubusercontent.com/16758464/125789027-1ca4b08e-44c5-432e-ac93-765a81c14a4c.png">

2021-07-15 12:39 UTC, anafilipadealmeida commented on packages/app-pages/components/AppPages/index.jsx
>    const selectedOrgInAppShell = user?.currentOrganization?.id;
Hey @federicoweber, I believe I spotted one of the issues 😄 useAccount doesn't seem to return data in the same format as useUser, so one of the steps here is to find all the references to `user?.currentOrganization` and replace them by `user?.account?.currentOrganization`. This will make the organizations and profiles redux store update accordingly, as right now the selectedOrg is returning undefined!

2021-07-15 13:03 UTC, anafilipadealmeida commented on packages/app-shell/components/AppShell/index.jsx
> -  manageChannelsURL,
A note of joy 😂 How good it is to see this all go away

2021-07-15 15:12 UTC, federicoweber commented
Hey @anafilipadealmeida, thanks for looking at this.
> I have a question: how do we now load publish with the navigator? I wanted to quickly check the route change scenarios with the navigator as well!

The two apps will load independently, the `LoadingGate` is using piping to the `accountContext`, but there is also a lot of the RPCs logic in position for the account, that is driving the loading. That is also what is making tricky to debug the flow for me, so many events bouncing around 😅 .

> Hey @federicoweber, I believe I spotted one of the issues 😄 useAccount doesn't seem to return data in the same format as useUser, so one of the steps here is to find all the references to user?.currentOrganization and replace them by user?.account?.currentOrganization. This will make the organizations and profiles redux store update accordingly, as right now the selectedOrg is returning undefined!

Ah goo catch 🙌

2021-07-15 17:19 UTC, hamstu commented
@federicoweber The `enabledApplicationModes` error is ok 👍🏻  Happens locally too when you have no application Modes in the db, and so it's not a concern. I think since now staging is using a fresh DB there are also no application modes defined there.

2021-07-15 17:28 UTC, hamstu requested changes
Just some style nits I think - otherwise this looks good to me!

2021-07-15 17:28 UTC, hamstu commented on packages/web/index.jsx
> +  }, [])
💅🏻  Can you make sure you run `prettier` on all these changes? 😄

2021-07-15 17:28 UTC, hamstu commented on packages/accountContext/index.js
> +import gql from 'graphql-tag'
Is this the same as `gql` from `@apollo/client`?

2021-07-15 17:28 UTC, hamstu commented on packages/app-shell/components/AppShell/index.jsx
> -  manageChannelsURL,
🥳  🗑️   Agreed! At this point, do we even need this component/file anymore @federicoweber? 🤔

2021-07-15 17:28 UTC, hamstu commented on webpack.config.dev.js
> +      NAVIGATOR_URL: 'https://components.buffer.com/navigator.js',
😲  So cool to see this! Micro Frontends for the win! (I know we're not all the way there, but this is still really cool.)

2021-07-15 17:39 UTC, federicoweber commented on packages/app-shell/components/AppShell/index.jsx
> -  manageChannelsURL,
Yeah, I agree we could simplify this and maybe fully remove the `app-shell` but I'm hesitant to do it not being too familiar with the codebase. Also I prefer to keep the changes to a functional minimum for this PR. Maybe that is something you can follow up with @hamstu ?

2021-07-15 17:41 UTC, federicoweber commented on packages/accountContext/index.js
> +import gql from 'graphql-tag'
Good one, I think so 🤔

2021-07-15 18:27 UTC, hamstu commented on packages/app-shell/components/AppShell/index.jsx
> -  manageChannelsURL,
For sure! That's fine with me. 😄

2021-07-15 18:28 UTC, hamstu approved these changes

2021-07-19 15:33 UTC, anafilipadealmeida commented
@federicoweber and @hamstu, are you able to see the navigator in the staging branch?

2021-07-19 15:59 UTC, federicoweber commented
> @federicoweber and @hamstu, are you able to see the navigator in the staging branch?

Hey @anafilipadealmeida, no I noticed that on Thursday, it's not injecting the script URL for the Navigator on staging. WIll fix that before merging 😉

2021-07-19 21:32 UTC, merged