Add preview card component
bufferapp/buffer-publish pull request #1845
Opened 2021-07-25 08:37 UTC by daltino

### Description

Add Preview Card, which will receive the other components as children, and have box-shadow and border

### Context & Notes

Needed for post previews

https://buffer.atlassian.net/browse/PUB-3712

### Screenshots (if appropriate)
![Preview Card in Storybook](https://share.buffer.com/o0ue56x2)

### Best Practices Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-07-26 10:32 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  min-height: 128px;
Hey @daltino, I don't think you need any min-height here

2021-07-26 10:33 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  position: relative;
I'm curious, why using a position relative on the card, and also justify the content with space-between?

2021-07-26 10:43 UTC, anafilipadealmeida requested changes

2021-07-26 10:43 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  padding: 10px;
<img width="564" alt="Screenshot 2021-07-26 at 11 34 14" src="https://user-images.githubusercontent.com/16758464/126975502-2eadcab7-e97f-464c-874e-8d7b0a10e4a8.png">
If you look at the preview, each component inside the card has its own background color and occupies the 100% width of the card, so you should be adding the paddings and margins to it instead of the card

2021-07-26 13:13 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  min-height: 128px;
Ok will fix that

2021-07-26 13:14 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  padding: 10px;
Yup i realized this while working on the other parts of the card :)

2021-07-26 13:16 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  min-height: 128px;
For this i wanted the card to be visible so I'm using a height of 60px

2021-07-27 11:48 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  margin-bottom: 8px;
Why are we keeping a margin bottom in this card?

2021-07-27 12:00 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  margin-bottom: 8px;
Ok removing that

2021-07-27 17:24 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +}
Hey @daltino, there are some code formatting errors that eslint will flag, like the missing `;` here  . Did you get a chance to set [Prettier](https://github.com/bufferapp/buffer-publish/blob/main/CONTRIBUTING.md)? We've been using it in our IDE so we don't have to worry about formatting!

2021-07-28 14:46 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +}
Ok formatted thanks for spotting.

2021-07-28 15:11 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  grayLight,
@daltino, did you run prettier in this file?

2021-07-28 15:51 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  grayLight,
Don't we have a lint command that does all the lining, would have been helpful

2021-07-29 09:14 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  grayLight,
I recommend following the https://prettier.io/docs/en/editors.html, we are all using the option formatOnSave, as every time we change and save a file, it runs prettier for us. The discussion on either having a pre-commit or not happened here: https://threads.com/34371831115

2021-07-29 09:17 UTC, anafilipadealmeida approved these changes

2021-07-29 10:27 UTC, merged