Preview campaign bar component
bufferapp/buffer-publish pull request #1850
Opened 2021-07-26 13:12 UTC by daltino

### Description

Add campaign bar to post previews component

### Context & Notes

It adds the campaign bar to post previewsl.

https://buffer.atlassian.net/browse/PUB-3714

### Screenshots (if appropriate)
![Preview with Campaign Bar](https://p-bofz5w.t2.n0.cdn.getcloudapp.com/items/v1uYZGlR/a978c854-493e-4960-9bc8-7584c1c3a3e1.png?source=viewer&v=1fa6359dbbb10c1fccd05ce53a41649e)

### Best Practices Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-07-27 18:51 UTC, anafilipadealmeida requested changes
Hey @daltino, I wonder if we could also add `text-overflow: ellipsis;` as we spoke in our call, so we can handle longer names nicely in the ui

2021-07-27 18:51 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +            role="img"
I recommend this article on accessibility in svg (https://css-tricks.com/accessible-svgs/#example-2-standalone-icon-decorative). You might have gotten the inspiration for adding the role to the icon from `<PostItem>` but these 2 cases are slightly different. In the case of the PostItem, the icon is a Standalone Icon, Meaningful. That's why for accessibility we use a combination of title and role. In this case you have the name of the campaign, so the icon is just decorative and doesn't need it.

2021-07-27 18:51 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  margin: -2px 0 0 8px;
I'm not sure what you're trying to achieve here but I'd avoid using negative margins if possible

2021-07-27 18:51 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  color: ${white};
UI Text components accept a color prop, so you don't need to add css for that: https://bufferapp.github.io/ui/#/ui/ui/text

2021-07-27 18:51 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  display: flex;
Flexbox is used for layout, to align multiple elements. If the `<Text>` doesn't have any children, you don't need it. I'd recommend reading the css tricks guide on [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

2021-07-29 10:41 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +            role="img"
Ok got it.

2021-07-29 10:44 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  color: ${white};
Ok good point!

2021-07-29 10:44 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  display: flex;
Ok noted!

2021-07-29 10:45 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  margin: -2px 0 0 8px;
I wanted to align the icon and text correctly, but I can remove this.

2021-07-29 14:06 UTC, daltino commented
@anafilipadealmeida regarding the `text-overflow: ellipsis;` the `type='label'` handles from looking at the label styling, what do you think?

2021-07-29 14:33 UTC, anafilipadealmeida commented
> @anafilipadealmeida regarding the `text-overflow: ellipsis;` the `type='label'` handles from looking at the label styling, what do you think?

🤔 The thing here is that you are using an incorrect semantic element, as labels are for inputs, selects and textareas. The most appropriate element to use here is a type="p", which I believe you'll have to adjust in styles (it doesn't come with text-overflow)

2021-07-29 16:54 UTC, daltino commented
> > @anafilipadealmeida regarding the `text-overflow: ellipsis;` the `type='label'` handles from looking at the label styling, what do you think?
> 
> 
> 
> 🤔 The thing here is that you are using an incorrect semantic element, as labels are for inputs, selects and textareas. The most appropriate element to use here is a type="p", which I believe you'll have to adjust in styles (it doesn't come with text-overflow)

Ok I will make use type="p" and apply the styling.

2021-08-02 09:59 UTC, anafilipadealmeida requested changes

2021-08-02 09:59 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
<img width="393" alt="Screenshot 2021-08-02 at 10 52 40" src="https://user-images.githubusercontent.com/16758464/127842541-4b0f6416-bb15-44c7-ae41-d7cf63081e64.png">
 These are the colors campaigns can have at the moment. If the name of the campaign is always white, against background colors like yellow it will not be accessible, as it fails the color contrast test. I'd encourage you to reach out to Lauren to ask which campaign colors should have dark icon and text instead

2021-08-02 09:59 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/style.js
> +  border-radius: ${borderRadius} ${borderRadius} 0px 0px;
To align both the icon and text you need `align-items: center;`

2021-08-02 12:16 UTC, daltino commented on packages/calendar/components/PostPreview/style.js
> +  border-radius: ${borderRadius} ${borderRadius} 0px 0px;
Ok good point!

2021-08-02 12:18 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
Ok will reach out to lauren on this. Thanks ana!

2021-08-02 14:15 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
I added some logic to switch the campaign text or icon color, the only concern is how do we maintain the list of lighter colors that require dark text. @anafilipadealmeida

2021-08-02 14:25 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
Another option could be if we choose to SCSS lightness($color) function to check the campaign color and infer the text or icon color.

2021-08-03 09:02 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
I confirmed with Lauren, there are only two colors `pinkLighter, yellow` that need dark text.

2021-08-03 14:06 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +  const lighterCampaignColors = [pinkLighter, yellow];
Hey @daltino, even though this works for now, it's gonna be difficult to maintain. Imagine someone adds or removes colors from campaigns, this will no longer work properly, and nobody will know we have to update a piece of code inside the calendar. I believe the best way is to create a utils function [example1](https://stackoverflow.com/questions/35969656/how-can-i-generate-the-opposite-color-according-to-current-color), [example2](https://gomakethings.com/dynamically-changing-the-text-color-based-on-background-color-contrast-with-vanilla-js/) that we can call here to generate the text color

2021-08-03 14:43 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +  const lighterCampaignColors = [pinkLighter, yellow];
@anafilipadealmeida yh i pointed out this question yesterday in the conversation. I will follow the example util functions thanks 😄

2021-08-03 17:38 UTC, anafilipadealmeida requested changes

2021-08-03 17:38 UTC, anafilipadealmeida commented on packages/calendar/utils/getContrastColor.js
> +  }
Hey @daltino, this is not following our prettier and eslint rules, do you have your setup 100% working?

2021-08-03 17:38 UTC, anafilipadealmeida commented on packages/calendar/utils/getContrastColor.js
> +  return (yiq >= 128) ? 'black' : 'white';
I'd use the colors from ui repo. Also, if you take a look at the figma file you'll see we don't use black for text, but a grayDarker instead.

2021-08-03 18:49 UTC, daltino commented on packages/calendar/utils/getContrastColor.js
> +  }
For my setup I switch Format on Save in VSCode I will double check this once more @anafilipadealmeida

2021-08-03 18:49 UTC, daltino commented on packages/calendar/utils/getContrastColor.js
> +  return (yiq >= 128) ? 'black' : 'white';
Got it will update.

2021-08-04 09:16 UTC, anafilipadealmeida requested changes

2021-08-04 09:16 UTC, anafilipadealmeida commented on packages/calendar/utils/getContrastColor.js
> +  return yiq >= 128 ? black : white;
if you take a look at the figma file you'll see we don't use black for text, but a grayDarker instead.

2021-08-04 11:20 UTC, daltino commented on packages/calendar/utils/getContrastColor.js
> +  return yiq >= 128 ? black : white;
Ah ok got it

2021-08-04 14:52 UTC, MayaUribe commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
@daltino Sorry for the ceiling-cat here, but wanted to mention that we already have a function in place for getting the color contrast, in case is helpful 👀

https://github.com/bufferapp/buffer-publish/blob/dfd7325b0aff0b4bf7988a37c8fe4452943187aa/packages/shared-components/ColorPicker/utils/HexValidations.js#L3

2021-08-04 14:54 UTC, MayaUribe commented on packages/calendar/components/PostPreview/story.jsx
> +  .add('simple w/ Campaign', () => (
Hey @daltino what does w/ means on this line? I'm not sure it's too clear 🤔 I think is best to default to the full words to make the code super clear and non-ambiguous

2021-08-04 14:57 UTC, MayaUribe requested changes
Hey @daltino I added a couple of comments, but basically, we already have some logic in place for the contract color, we use it in the Shop Grid section where users can basically pick any color they want, please make sure not to duplicate the already existing logic 🙏
Thank you!

2021-08-04 14:57 UTC, MayaUribe commented on packages/calendar/utils/getContrastColor.js
> +};
@daltino as I mentioned on the other comment, we already have this logic in place -> https://github.com/bufferapp/buffer-publish/blob/dfd7325b0aff0b4bf7988a37c8fe4452943187aa/packages/shared-components/ColorPicker/utils/HexValidations.js#L3

I would avoid duplicating this logic 🙏

2021-08-04 15:36 UTC, daltino commented on packages/calendar/components/PostPreview/story.jsx
> +  .add('simple w/ Campaign', () => (
We use it to mean `with` we have it in other stories as well, I presume it's to keep the names short in storybook @MayaUribe

2021-08-04 15:45 UTC, anafilipadealmeida commented
> Can you point me to this existing code just to be sure @MayaUribe thanks.
Hey @daltino, @MayaUribe did it, please read the comments: 
<img width="844" alt="Screenshot 2021-08-04 at 16 42 47" src="https://user-images.githubusercontent.com/16758464/128211461-61e1fe6e-b3d6-473d-8437-9cc30a561b88.png">

We have two options here, since the other utils function returns black and white, and we want grayDark and white. We either keep both utils and live with it, or tweak the old one to support both options (preferable)

2021-08-04 16:03 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +          <CampaignText type="p" color="white">
Thanks

2021-08-16 12:58 UTC, anafilipadealmeida requested changes

2021-08-16 12:58 UTC, anafilipadealmeida commented on packages/shared-components/ColorPicker/utils/HexValidations.js
> +  return yiq >= 160 ? grayDarker : white;
Please move this back to black and white, if you change the shared-component you'll be causing a UI regression (as there are other places that use black and not grayDark). See this in combination with the comment in: packages/calendar/components/PostPreview/index.jsx

2021-08-16 12:58 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +            color={textAndIconColor === grayDarker ? 'grayDarker' : 'white'}
```suggestion
            color={textAndIconColor === black ? 'grayDarker' : 'white'}
```

2021-08-16 13:19 UTC, anafilipadealmeida commented on packages/shared-components/ColorPicker/utils/HexValidations.js
> +  return yiq >= 160 ? grayDarker : white;
Please see the comment/suggestion in: packages/calendar/components/PostPreview/index.jsx, as I believe that's the extra logic you are mentioning. There's no need for a flag in the utils function, we can just override the darker color in PostPreview

2021-08-16 14:02 UTC, daltino commented on packages/calendar/components/PostPreview/index.jsx
> +            color={textAndIconColor === grayDarker ? 'grayDarker' : 'white'}
Ok @anafilipadealmeida I discussed this with Lauren last week just so you know and she's aware of this change we decided to go with

2021-08-16 14:04 UTC, anafilipadealmeida commented on packages/calendar/components/PostPreview/index.jsx
> +            color={textAndIconColor === grayDarker ? 'grayDarker' : 'white'}
@daltino, where can I find that discussion?

2021-08-16 14:05 UTC, daltino commented on packages/shared-components/ColorPicker/utils/HexValidations.js
> +  return yiq >= 160 ? grayDarker : white;
Ok your suggestion makes sense

2021-08-16 23:38 UTC, anafilipadealmeida approved these changes
I pushed a change to make the icon color match the text color. It's good to go

2021-08-16 23:51 UTC, merged