[PUB-3769] adds switcher week and month tracker
bufferapp/buffer-publish pull request #1875
Opened 2021-08-25 15:32 UTC by jezebelbaal

### Description

Adds tracker to both buttons month and week at calendar switcher.

### Context & Notes
Related track: [https://buffer.atlassian.net/browse/PUB-3769](https://buffer.atlassian.net/browse/PUB-3769)

### Screenshots (if appropriate)

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-08-25 15:34 UTC, jezebelbaal commented on packages/calendar/index.js
> +      const metadata = {
I'm assuming that when someone clicks the switcher, the person comes from the other view (from month to week i.e.) though it might not always be right. Someone might click it and not switch views. I'm making this assumption and if it's the case we can acess it more assertively through state.

2021-08-30 09:35 UTC, anafilipadealmeida requested changes

2021-08-30 09:35 UTC, anafilipadealmeida commented on packages/calendar/index.js
> +      const metadata = {
Hey @jezebelbaal, it's a great observation. When doing tracking it's recommended that we make the least amount of assumptions possible, as we want accurate data and there might be surprises. In this case, users can indeed use the toggle on the same view, so the idea is to pass the isWeekly flag to both functions: https://github.com/bufferapp/buffer-publish/blob/main/packages/calendar/components/Calendar/index.jsx#L79-L80

2021-09-01 13:10 UTC, anafilipadealmeida approved these changes
![](https://media4.giphy.com/media/4T1FNki1P8Dgj74SRw/giphy.gif)

2021-09-01 14:55 UTC, merged