adds navigation redux connector with trackers
bufferapp/buffer-publish pull request #1878
Opened 2021-08-31 02:33 UTC by jezebelbaal

### Description

### Context & Notes

### Screenshots (if appropriate)

### Best Practices Checklist

-   [ ] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [ ] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-09-01 13:00 UTC, anafilipadealmeida reviewed
Hey @jezebelbaal , this is looking good! You are just missing the tracking for the OnTodayClick!

2021-09-02 13:19 UTC, anafilipadealmeida requested changes

2021-09-02 13:23 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.js
> +import { connect } from 'react-redux';
Is this file from this PR?

2021-09-02 14:04 UTC, jezebelbaal commented on packages/calendar/index.js
> +import { actions as analyticsActions } from '@bufferapp/publish-analytics-middleware';
you're right. thanks, Ana!

2021-09-02 14:05 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.js
> +import { connect } from 'react-redux';
Nope! Sorry for that. 😅

2021-09-02 17:03 UTC, anafilipadealmeida approved these changes
🚀 🚀

2021-09-02 23:58 UTC, hamstu approved these changes
Looks great – nice work @jezebelbaal 😄

2021-09-06 11:44 UTC, merged