[PUB-3767]Add channel filter tracker
bufferapp/buffer-publish pull request #1887
Opened 2021-09-06 15:13 UTC by jezebelbaal

### Description

This PR adds a tracker for both:

Channel Filtered: when user loads calendar and there are channels filtered
Channel Selected: when user intentionally selects channels at Channel Filter.

### Context & Notes

This is the related task: [https://buffer.atlassian.net/browse/PUB-3767](https://buffer.atlassian.net/browse/PUB-3767)

### Screenshots (if appropriate)

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [ ] I have tested different user stories.
-   [x] I have identified similar or related features and tested they are still working.
-   [ ] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-09-08 10:03 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +      isViewOnly
Does the handleFilteredChannels function accept 3 arguments?

2021-09-08 12:41 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +      isViewOnly
That was wrong, in fact 😅

2021-09-08 13:54 UTC, anafilipadealmeida reviewed
@jezebelbaal , did you test this in staging with channels?
If I load the calendar, having 8 channels selected, I see 2 tracking events for channels filtered: one with both previousChannelCount and channelCount 0, and another one with previousChannelCount 8
<img width="1675" alt="Screenshot 2021-09-08 at 14 52 55" src="https://user-images.githubusercontent.com/16758464/132522434-3ce642e1-9904-4f8f-b9e0-eb4666ca34f9.png">

2021-09-08 22:03 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +  const handleFilteredChannels = (beforeFilterCount, afterFilterCount) => {
Hi, @anafilipadealmeida 

On this bug matter, I realized that when we have enter an empty channels state, the tracker would be called; we emulate a click using `onSelectAllClick` on load.

So I wonder if can we make assumptions:
I assume that when I enter an empty state channels page (reload, i.e), my previous count will be zero. Does that make sense?

2021-09-08 22:14 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +  const handleFilteredChannels = (beforeFilterCount, afterFilterCount) => {
Also, should I make the refactorings from Code Climate?

2021-09-09 15:14 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +          handleSelectedChannels(channelsSelected.length, channels.length);
This line will also need to be adjusted to something like this:
```suggestion
          handleSelectedChannels({
            beforeFilterCount: channelsSelected.length,
            afterFilterCount: channels.length,
      });
```

2021-09-13 13:23 UTC, anafilipadealmeida requested changes
Hey @jezebelbaal, I left you a couple of comments here 🙂

2021-09-13 13:23 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +            afterFilterCount: channels.length,
While tracking channels selected, the previousChannelCount is the number of channels selected before this click happened. The channelCount is how many channels are selected after this click happened. Summing up, one is the previous channelsSelected state, the other one is the current channelsSelected state.

2021-09-13 13:26 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +        beforeFilterCount: channels.length,
Since when the page loads this is the first code to run, this can be replaced:
```suggestion
        beforeFilterCount: 0,
```

2021-09-13 13:27 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +        beforeFilterCount: numberOfChannelsSelected,
Since this only runs when there are no channelsSelected,
```suggestion
        beforeFilterCount: 0,
```

2021-09-13 14:20 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +        beforeFilterCount: numberOfChannelsSelected,
Makes sense, Ana! Thanks : )

2021-09-13 14:51 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/index.jsx
> +            afterFilterCount: channels.length,
Just to make it clear @jezebelbaal , that's not what's happening here at the moment ☝️ By using the `channels.length`, you'll always get the same value

2021-09-14 02:55 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +            afterFilterCount: channels.length,
Hi, @anafilipadealmeida! Sorry it took me a while to figure this out and asked for your review before finishing it. Came up with a solution; maybe not the most elegant, though I tested across a couple more of scenarios and it seems to work. Thanks for your support and patience on this!

2021-09-14 13:00 UTC, anafilipadealmeida reviewed
Hey @jezebelbaal, I'm attaching here what I'm currently seeing for the channelsSelected: tracking  https://share.getcloudapp.com/kpunR782. All 9 channels are selected. When I unselect 1, there are 8 now 👍 . However, as soon as I click on select all, instead of the tracking event to have an old state of 8 and a new of 9, it always returns 9 and 0.

My suggestion would be to remove the Channel Selected tracking event from this PR and deploy the Channel Filter, as it's ready, and pair with @MayaUribe on the other event 😊

2021-09-14 13:00 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +  const previousChannelCount = setChannels.length;
This setChannels is a function to set the state in React (the equivalent to useCount here: https://reactjs.org/docs/hooks-state.html). I assume what you'd want here is the length of the state array, which would be channelsSelected

2021-09-14 13:00 UTC, anafilipadealmeida commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +    if (!defaultSelected) {
I'm curious, what is the defaultSelected? I saw we are setting it to false for clicks on each channel and true for clicks to select all channels, but I'm wondering what's it for?

2021-09-14 13:26 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +    if (!defaultSelected) {
This is being used because selectAllClick is being used by when the page loads and when someone clicks the item. So I'm avoiding call the select tracking when it's being called by the filtering function.

2021-09-14 13:30 UTC, MayaUribe commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +    if (!defaultSelected) {
> My suggestion would be to remove the Channel Selected tracking event from this PR and deploy the Channel Filter, as it's ready, and pair with @MayaUribe on the other event 😊

Heya @jezebelbaal I agree with @anafilipadealmeida on splitting the work here 💯 would you be up for separating the `Calendar Channels Selected` into a different PR and we can pair on it together? 😊

2021-09-14 13:34 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +  const previousChannelCount = setChannels.length;
Hey Ana, that sounds better on. I faced this bug on selecting all, but weirdly I thought I could fix it. Will split them and probably it will be easier to review. Thanks for the inputs!

2021-09-14 13:45 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/generateFilterItems.jsx
> +    if (!defaultSelected) {
Sure! 🏃‍♀️

2021-09-14 15:03 UTC, MayaUribe approved these changes
I added a comment for readability @jezebelbaal 🙂

2021-09-14 15:03 UTC, MayaUribe commented on packages/calendar/components/ChannelFilter/index.jsx
> +  const handleFilteredChannels = ({ beforeFilterCount, afterFilterCount }) => {
A small one @jezebelbaal: I think we should rename this function so it's clear we are tracking, since `handle` can be very generic, it's very useful as we are reading the code in the future to easily detect that this piece is for tracking where we use it.

2021-09-14 15:03 UTC, MayaUribe commented on packages/calendar/components/ChannelFilter/index.jsx
> +  const handleFilteredChannels = ({ beforeFilterCount, afterFilterCount }) => {
We could either rename it or just use the `trackChannelsFiltered` directly :)

2021-09-14 15:49 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +  const handleFilteredChannels = ({ beforeFilterCount, afterFilterCount }) => {
that's right, @MayaUribe! in this case, all the props are properly available to this level, so no need to wrap this up. just called the straight tracker one instead :)

2021-09-14 15:57 UTC, MayaUribe approved these changes
Thank you @jezebelbaal 🚀

2021-09-14 17:20 UTC, anafilipadealmeida approved these changes

2021-09-14 17:27 UTC, merged