[PUB-3806] Adds tracker to Channel Selection
bufferapp/buffer-publish pull request #1901
Opened 2021-09-15 19:57 UTC by jezebelbaal

#Description

This PR adds tracker to channel selections on click.
Context & Notes

https://buffer.atlassian.net/browse/PUB-3806

### Screenshots (if appropriate)

### Best Practices Checklist

-   [x] My code follows the code style and guidelines of this project. 
-   [ ] I have added tests to cover my changes.
-   [x] I have tested different user stories.
-   [x] I have identified similar or related features and tested they are still working.
-   [x] I have performed a self-review of my own code.
-   [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
-   [ ] I have commented my code, particularly in hard-to-understand areas.
-   [ ] I kept accessibility in mind by following the [a11y checklist.](https://www.notion.so/buffer/Workflow-Checklist-e64d86eb795140bcbfdc16d1c72e573f)
-   [ ] I have considered [security, abuse & compliance](https://www.notion.so/buffer/Engineering-Wiki-f34142d290304c35bebadf76cc9cc89e#cc6dcc7617184227b77da2e1b262a563) implications of my changes.

### ⚠️ Pre-deploy Checklist

- [ ] I have manually loaded the URL of the staging deployment and confirmed it's working (see below**)
- [ ] I have confirmed that the Cypress E2E test is passing (_Note: we have a known issue where it doesn't run on some PRs. Hopefully this will be fixed soon._)
- [ ] I have confirmed that all other tests are passing.

** To visit the URL of the staging deployment, please vlick the link in the bot comment, or look under checks at the bottom of this PR and click "Details" next to `bufferbotbrains/cicd-buffer-publish`
![image](https://user-images.githubusercontent.com/809093/116589853-f2331f80-a8d1-11eb-8bd2-6e23cde1c867.png)

2021-09-15 22:37 UTC, federicoweber requested changes
Hey, @jezebelbaal thanks for working on this one.
I think the overall logic looks good, but I've left a few comments in the code on a couple of things I would love to address before shipping this one.

Especially I think it's important to add some unit tests to make sure we are properly tracking the events. Otherwise, it could be easy to accidentally introduce regressions that can go unnoticed for some time as the tracking has no visible effect :).

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: 1,
Why these two values are hardcoded?
Shouldn't be based on the actual count?

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
Same in here 🤔.
Reading the comments I see those will depend on the navigation path, but disregarding the cause of the filter shouldn't the `channelsSelected` always be the source of truth?

Do you think we could consolidate all this into the `useTrackChannelChange` hook?

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
I was under the impression we wanted to count `channelsSelected`. What is the reason we are counting all channels in here?

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackChannelChange.js
> +function useTrackChannelChange(
Thinking about this, probably `useTrackSelectedChannels` will be a better name 😉 .

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackChannelChange.js
> +    }
A small one, this logic is a bit hard to read maybe we can abstract the conditional into named variables?
Something like:
```
const isChannelsListsInitialized =  !hasChannels && channelsSelected.length > 0
const isPreviousChannelCountValid = previousState !== -1
```

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackChannelChange.js
> +  const [previousState, setPreviousState] = useState(-1);
Let's rename `previousState` into `previousChannelsCount` it will make things a bit easier to read 😉.

2021-09-15 22:37 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackChannelChange.js
> +      });
It could be worth adding a few unit tests to make sure we are calling the tracking correctly.
Let me know if you want to pair to set those up 🙂

2021-09-16 11:38 UTC, jezebelbaal commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
Hi Fed! In this case, the setChannels right after will change the channelsSelected. In these case, we are setting up by default on the first load all available channels. This is why we don't get from channelsSelected. These are the exact scenarios we prevented from being tracked at our created hook, and will be tracked  differently.

2021-09-16 13:46 UTC, MayaUribe commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: 1,
Hey @federicoweber! I think the reason is that we are selecting these ones by default on the first load, and by default, it could be either all the channels or one specific channel.

2021-09-16 13:56 UTC, MayaUribe commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
> Do you think we could consolidate all this into the useTrackChannelChange hook?
I think it'd be great to consolidate things into the same hook, considering that we have two different ways to track this: the default channel selection (when we load the calendar page) and the manual channel selection (when the user actively filters the channels), at the moment the hook is only accounting for the later.

> I was under the impression we wanted to count channelsSelected. What is the reason we are counting all channels in here?
On this piece specifically is because we are auto-selecting all channels, so we want to track that action.

Let me know if that help @federicoweber 😊

2021-09-16 18:14 UTC, federicoweber approved these changes
Looks good to me @jezebelbaal thank you 🙌 :shipit:

2021-09-16 18:14 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
Hey @MayaUribe talking with @jezebelbaal about this we decided not to refactor this part of the tracking for the moment.
The reason is that we are also using those conditionals to execute side effects (`onSelectAllClick`, and `setChannels`), which shouldn't be part of the tracking hook.

I think long term it will be beneficial to revisit this logic to properly separate the concerns, but given that we want to go live on Monday, and this is currently working fine, let's go roll with it😉.

2021-09-16 18:14 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackSelectedChannels.js
> +    }
So much easier to read, thanks @jezebelbaal 🙌

2021-09-16 18:14 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
@anafilipadealmeida, @mallen5311 I have a question not related to the PR. 
I would love to understand why we are tracking these two cases, given that they are default values, and not triggered by a user action.

Thanks!

2021-09-16 18:31 UTC, federicoweber commented
hey @jezebelbaal I see one of the tests is failing, can you please take a look at that before merging :).
Thanks!

2021-09-16 19:49 UTC, federicoweber commented on packages/calendar/components/ChannelFilter/index.jsx
> +        channelCount: channels.length,
hey @anafilipadealmeida and @jwinternheimer, I might be wrong but following our slack [conversation](https://buffer.slack.com/archives/C151RRDL1/p1631817838405800) I think we are using these events the other way around.
If I understand this correctly:
-  `Calendar Channels Filtered` should the user action (filtering from the dropdown)
-  `Calendar Channels Selected` should the automatic action (on calendar load)

If that's the case we will need to flip the two events @jezebelbaal

2021-09-16 22:31 UTC, federicoweber commented on packages/calendar/components/hooks/useTrackFilteredChannels.test.js
> +import useTrackFilteredChannels from './useTrackFilteredChannels';
hey @jezebelbaal I've moved this in here because it's only testing the actual hook :)

2021-09-17 00:28 UTC, merged